services:
  angular-app:
    build: ./frontend/projetglop-front  # Dockerfile dans le répertoire front
    ports:
      - "8081:80"  # Angular sera accessible via localhost:8081
    depends_on:
      - springboot-app

  springboot-app:
    build: ./backend/projetglop-backend  # Dockerfile dans le répertoire back
    ports:
      - "8080:8080"  # Spring Boot accessible via localhost:8080
    env_file:
      - .env
    depends_on:
      - postgres-db
    command:  ["sh", "-c", "./wait-for-it.sh postgres-db:5432 -- java -jar app.jar"]

  postgres-db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"  # PostgreSQL sera accessible via localhost:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d assurances_db_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
