name: Feature Branch CI

on:
  push:
    branches:
      - 'feature/*'  # Triggers on any feature branch push

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK for compilation
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Compile the backend project
      - name: Compile Backend Project
        working-directory: .
        run: |
          mvn clean compile
          echo "Compilation successful"

  build-and-test:
    runs-on: ubuntu-latest
    needs: compile  # Ensure this job runs after the compile job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK for Spring Boot backend
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Install backend dependencies and run JUnit tests
      - name: Run Backend JUnit Tests
        working-directory: .
        run: |
           mvn install
           mvn test

