name: CI/CD Pipeline Dev

on:
  pull_request:
    branches:
      - develop

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK for compilation
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Compile the backend project
      - name: Compile Backend Project
        working-directory: ./backend/projetglop-backend
        run: |
          mvn clean compile
          echo "Compilation successful"

  build-and-test:
    runs-on: ubuntu-latest
    needs: compile # Ensure this job runs after the compile job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK for backend tests
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Run JUnit tests for backend
      #- name: Run Backend JUnit Tests
      #  working-directory: ./backend/projetglop-backend
      #  run: |
      #    mvn install
      #    mvn test

      - name: Test Backend Setup # for testing the cicd
        working-directory: ./backend/projetglop-backend
        run: |
          echo "Testing Backend: Verifying Maven installation"
          mvn -version
          echo "Backend setup test succeeded"
